name: "datawise-build-yarn"
description: "datawise build yarn"
inputs: 
  NODE_VERSION:
    required: true
runs:
  using: "composite"
  steps:

    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        registry-url: 'https://npm.pkg.github.com'

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: |
          ${{ github.workspace }}/.next/cache
          .npm
          .yarn
        key: ${{ runner.os }}-nextjs2-${{ hashFiles('**/package-lock.json','**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-nextjs2-${{ hashFiles('**/package-lock.json','**/yarn.lock') }}-
    
    - name: yarn set cache
      shell: bash 
      run: yarn config set cache-folder .yarn

    - name: yarn install
      shell: bash 
      run: yarn install

    - name: yarn build
      shell: bash 
      run: yarn build

